# Generated by Django 3.2.12 on 2022-11-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, default='https://chookbae.s3.ap-northeast-1.amazonaws.com/img/0ab010c45f1811ed8ffe0242c0a80002', null=True),
        ),
    ]
