# Generated by Django 3.2.12 on 2022-10-27 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('cert_num', models.CharField(max_length=200)),
                ('cert_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'emailcert',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_status', models.IntegerField()),
                ('match_name', models.CharField(max_length=200)),
                ('match_type', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
                ('name_language', models.CharField(max_length=200)),
                ('player_image', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('birthday', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('current_team', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200)),
                ('goal', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('yellow_card', models.IntegerField()),
                ('red_card', models.IntegerField()),
                ('run_time', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=200)),
                ('logo', models.TextField(blank=True, null=True)),
                ('group', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('points', models.IntegerField()),
                ('last_five', models.CharField(max_length=200)),
                ('goal_diff', models.IntegerField()),
                ('manager', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('login_date', models.DateField()),
                ('login_count', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_image', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('opened_year', models.IntegerField()),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='worldcup.match')),
                ('win', models.IntegerField(default=0)),
                ('draw', models.IntegerField()),
                ('loss', models.IntegerField()),
            ],
            options={
                'db_table': 'bet',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bet_time', models.DateTimeField()),
                ('user_point', models.IntegerField()),
                ('predict', models.IntegerField()),
                ('match_id', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.DO_NOTHING, to='worldcup.match')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='worldcup.user')),
            ],
            options={
                'db_table': 'prediction',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField()),
                ('info', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='worldcup.user')),
            ],
            options={
                'db_table': 'point',
            },
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.DO_NOTHING, to='worldcup.player')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='worldcup.user')),
            ],
            options={
                'db_table': 'playercard',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.DO_NOTHING, to='worldcup.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1_id', to='worldcup.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2_id', to='worldcup.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue_id',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.DO_NOTHING, to='worldcup.venue'),
        ),
    ]
