# Generated by Django 3.2.12 on 2022-10-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name_language',
            new_name='homename',
        ),
    ]
