# Generated by Django 3.2.12 on 2022-10-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='worldcup.match'),
        ),
    ]
