# Generated by Django 3.2.12 on 2022-10-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.DO_NOTHING, to='worldcup.team'),
        ),
    ]
