# Generated by Django 3.2.12 on 2022-10-27 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0002_alter_bet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1_id',
            field=models.ForeignKey(db_column='team1_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1_id', to='worldcup.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_id',
            field=models.ForeignKey(db_column='team2_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2_id', to='worldcup.team'),
        ),
    ]
