# Generated by Django 3.2.12 on 2022-11-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0004_prediction_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
