# Generated by Django 3.2.12 on 2022-10-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0005_rename_loss_bet_lose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
