# Generated by Django 3.2.12 on 2022-11-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0005_playercard_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCert',
        ),
    ]
